language: php
php:
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"
before_script: composer dumpautoload
script: phpunit
notifications:
    email:
        on_success: always
        on_failure: always
